# Introduction to Python - Chapter1 - LESSON 4 :  The collections
Objective:


*   Familiar with different collections: list, tuple, set 
*   Undestand conversions of collections

We've already encountered some simple Python types like numbers (`int`, `float`), strings (`str`) and booleans (`bool`). We'll now look at how to group multiple values into a collection, such as a list of numbers or a dictionary that we can use to store and retrieve key-value pairs. Many useful collections are built-in types in Python, and we will encounter them quite often.

## 1. The list (`list`)

The list type in Python is called `list`. We can use it to store multiple values and access them sequentially or by their position (their index). Lists are defined with a set of values separated by commas in square brackets (`[` and `]`):

In [3]:


# an emptylist
my_list = [1,2,3]
type(my_list)

list

In [6]:
one_variable = 2
another_variable = "4 strings"
third_variable = 3.9
# a list of variables defined elsewhere in the code
things = [
    one_variable,
    another_variable,
    third_variable, # This comma can be used in Python 3
]

print(things)
things

[2, '4 strings', 3.9]

[2, '4 strings', 3.9]

In [ ]:

print(things)

[2, '4 strings', 3.9]

As you can see, we have used plural names for most of our list variables. This is a common convention and it is useful to follow it in most cases.

To access an element of the list, we use the list identifier followed by the index in square brackets. The indexes are integers that start at zero:

In [12]:
animals =['cat', 'dog']

print(animals[0]) # cat
#print(numbers[1]) # 7

print(animals[-1])

print(len(animals))

cat
dog
2

In [ ]:
# This will give us an error, since the list contains only 4 elements
print(animals[6])

IndexError: list index out of range

We can also find elements starting from the end:

In [ ]:
print(animals[-1]) # The last item in the list
print(numbers[-2]) # The second last item in the list

bison
20

We can also extract a subset of a list (which will itself be a list) using a slice. This uses almost the same syntax as accessing a single element, but instead of specifying a single index in square brackets, we must specify an upper and lower bound. Note that our sublist will include the element at the lower bound, but exclude the element at the upper bound:

In [14]:
# a list of strings
animals = ['cat', 'dog', 'fish', 'bison', 'lion']

# a list of integers
numbers = [1, 7, 34, 20, 12]

In [15]:
print(animals[1:4]) # ['dog', 'fish'[

['dog', 'fish', 'bison']

In [16]:
print(animals[1:-1]) # ['dog', 'fish']

['dog', 'fish', 'bison']

If one of the boundaries is one of the ends of the list, we can leave it out.

In [17]:
print(animals[2:]) # ['fish', 'bison']

['fish', 'bison', 'lion']

In [19]:

#print(animals[-:]) # ['cat', 'dog']
print(animals[:]) # A copy of the entire list (deep copy)

['cat', 'dog', 'fish', 'bison', 'lion']

We can even include a third parameter to specify the step size:

In [ ]:

print(animals[::3]) # ['cat', 'fish']

['cat', 'bison']

Lists are mutable, we can change items, add or remove them. A list will change size automatically when we add or remove items:

In [ ]:
print(type(animals))

<class 'list'>

In [ ]:
print(animals)
# Assign a new value to an item in the list
animals[3] = "hamster"

# Adding an item to the end of the list
animals.append("squirrel")

# Deleting an item from the list
del animals[2]
print(animals)

['cat', 'dog', 'fish', 'bison', 'lion']
['cat', 'dog', 'hamster', 'lion', 'squirrel']

Since lists are mutable, we can change a variable in a list without giving it a completely new value. Remember that if we assign the same `list` value to two variables, any changes made to one variable will be reflected in the other:

In [ ]:
animals = ['cat', 'dog', 'goldfish', 'canary']
pets = animals # Both variables reference the same list

animals.append('aardvark')
print(pets) # farting is always the same list as animals

animals = ['rat', 'gerbil', 'hamster'] # Assigning a new list of values to animals
print(pets) # pets still refers to the old list

pets = animals[:] # assignment by *copy* of the values of the list to pets
animals.append('aardvark')
print(pets) # pets always contains the same initially assigned values

Run this code on pythontutor.com and watch the memory allocation performed by the interpreter

You can mix the types of values you store in a list:

In [ ]:
my_list = ['cat', 12, 35.8]

How do we check if a list contains a particular value? We use the operators `in` or `not in` :

In [ ]:
numbers = [34, 67, 12, 29]
number = 57

if number not in numbers:
    print("%d is not in the list!" % number)

number = 90
if number not in numbers:
    print("%d is not in the list!" % number)

57 is in the list!
90 is not in the list!

### The functions of lists


There are `built-in' functions that we can use on lists and other sequences:

In [38]:
animals = ['cat', 'dog', 'goldfish', 'canary']
# the size of a list
print(len(animals))
numbers = [1, 2, 3, 4, 5]
# the sum of a list of integers
print(sum(numbers))

4
15

The `list` object also has many useful functions:

In [51]:
numbers = [1, 2, 3, 4, 5]

# Adding an element at the end, already seen :)
numbers.append(5)

print(numbers)

[1, 2, 3, 4, 5, 5]

In [52]:
# Count the number of items in the list
numbers.count(5)

2

In [53]:
# add several values (at once) at the end
numbers.extend([56, 2, 12])
print(numbers)
numbers.append([56, 2, 12])
print(numbers)

[1, 2, 3, 4, 5, 5, 56, 2, 12]
[1, 2, 3, 4, 5, 5, 56, 2, 12, [56, 2, 12]]

In [54]:
# Find the index of a value in the list
print(numbers.index(3))
# If the value is present several times, the first index is obtained
print(numbers.index(5))
# If the value is not present in the list, the ValueError is returned!

2
4

In [57]:
# insert a value at a given index
numbers = [1, 2, 3, 4, 5]
print(numbers)
numbers.insert(0, 45) 
print(numbers)
numbers[0]

[1, 2, 3, 4, 5]
[45, 1, 2, 3, 4, 5]

45

In [62]:
numbers = [1, 2, 3, 4, 5]
my_number = numbers.pop()
print(my_number)
print(numbers)

5
[1, 2, 3, 4]

In [66]:
# delete an item from the list by specifying its value
numbers = [1, 2, 3, 4, 5]
numbers.remove(1)
print(numbers)

[2, 3, 4, 5]

In [68]:
numbers = [1, 2, 3, 4, 5]
numbers.append(5)
print(numbers)
# If the value occurs more than once, only the first occurrence is deleted
numbers.remove(5)
print(numbers)

[1, 2, 3, 4, 5, 5]
[1, 2, 3, 4, 5]

## 2. The tuples (`tuple`)

Python has another type of sequence called `tuple`. Tuples are similar to lists, but they are immutable. Tuples are defined with a set of values separated by commas in parentheses (`(` and `)`):

In [69]:
WEEKDAYS = ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')

We can use tuples in the same way as we use lists, except that we cannot modify them:

In [72]:
animals = ('cat', 'dog', 'fish')

# an empty tuple
my_tuple = ()

# we can access a single element
print(animals[0])

# we can get a slice
print(animals[1:]) # note that our slice will be a new tuple, not a list

# we can count values or look up an index
animals.count('cat')
animals.index('cat')

# ... but this is not allowed:
#animals.append('canary')
animals[1] = 'gerbil'

cat
('dog', 'fish')

TypeError: ignored

What are tuples used for? We can use them to create a sequence of values that we do not want to change.

## 3. The sets (`set`)


There is yet another type of sequence called `set`. A `set` is a collection of unique elements. If we add multiple copies of the same element to a `set`, the duplicates will be eliminated and we will be left with one of each element. Sets are defined with a set of values separated by commas between braces (`{` and `}`):

In [73]:
animals = {'cat', 'dog', 'goldfish', 'canary', 'cat'}
print(animals) # This set contains a single 'cat' element

{'dog', 'canary', 'goldfish', 'cat'}

We can do several operations on the sets:

In [74]:
even_numbers = {2, 4, 6, 8, 10}
big_numbers = {6, 7, 8, 9, 10}

# subtraction
print(big_numbers - even_numbers)

# union
print(big_numbers | even_numbers)

# intersection
print(big_numbers & even_numbers)

# numbers which are big or even but not both
print(big_numbers ^ even_numbers)

{9, 7}
{2, 4, 6, 7, 8, 9, 10}
{8, 10, 6}
{2, 4, 7, 9}

It is important to note that unlike lists and tuples, sets are not ordered. When we display a set, the order of the elements will be random. We can still order it if we need to (although the `sorted` function will return a list):

In [75]:
print(animals)
print(sorted(animals))

{'dog', 'canary', 'goldfish', 'cat'}
['canary', 'cat', 'dog', 'goldfish']

How do we declare an empty `set`? We need to use the `set` function. Dictionaries, which we will discuss in the next section, used braces before sets adopted them, so an empty set of braces is in fact an empty dictionary:

In [30]:
# empty dictionary
a = {}

# empty set
b = set()

## 4. The  `range`

We can generate a sequence of integers (called `range`) using the `built-in` function: `range`. The `range` are generators, we will see these in detail in the next section. For now, we just need to know that the numbers in the range are generated one by one, not all at once.
 
In the examples below, we convert each `range` to a `list` so that all the numbers are generated and we can display them

In [76]:
# displays integers from 0 to 9
print(list(range(10)))

# displays integers from 1 to 10
print(list(range(1, 11)))

# displays odd integers between 1 and 10
print(list(range(1, 11, 2)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 7, 9]

As you can see, if we pass a single parameter to the range function, it is used as the upper bound. If we use two parameters, the first is the lower bound and the second is the upper bound. If we use three, the third parameter is the step size. The default lower bound is zero and the default step size is one. Note that the range includes the lower bound and excludes the upper bound.

## 5. The dictionaries `dict`

The Python dictionary type is called `dict`. We can use a dictionary to store key-value pairs. The `dict` is defined with a set of key-value pairs separated by commas between braces (`{` and `}`). We use a colon to separate each key from its value. We access dictionary values in the same way as list or tuple elements, but we use keys instead of indices:

In [78]:
marbles = {"red": 34, "green": 30, "brown": 31, "yellow": 29 }

personal_details = {
    "name": "Jane Doe",
    "age": 38,
}

print(marbles["green"])
print(personal_details["name"])

# Key error


# mModification or value creation
marbles["red"] += 3
personal_details["name"] = "Jane Q. Doe"

30
Jane Doe

KeyError: ignored

The keys of a dictionary do not have to be strings, they can be of any immutable type, including numbers and even tuples. We can mix different types of keys and different types of values in a dictionary. Keys are unique, if we repeat a key we will overwrite the old value with the new one. When we store a value in a dictionary, the key does not need to exist - it will be created automatically:

In [35]:
battleship_guesses = {
    (3, 4): False,
    (2, 6): True,
    (2, 5): True,
}

surnames = {}
surnames["John"] = "Smith"
surnames["John"] = "Doe"
print(surnames) # 

marbles = {"red": 34, "green": 30, "brown": 31, "yellow": 29 }
marbles["blue"] = 30 # this will work
#marbles["purple"] += 2 # this will fail -- the increment operator needs an existing value to modify!

{'John': 'Doe'}

Here are some commonly used functions for `dict` objects:

In [82]:
marbles = {"red": 34, "green": 30, "brown": 31, "yellow": 29 }

# Get a value by its key, or None if it doesn't exist
marbles.get("orange")
# We can specify a different default
marbles.get("orange", 0)

# Add several items to the dictionary at once
marbles.update({"orange": 34, "blue": 23, "purple": 36})

# All the keys in the dictionary
#print(marbles.keys())
# All the values in the dictionary
#marbles.values()
# All the items in the dictionary
marbles.items()

dict_items([('red', 34), ('green', 30), ('brown', 31), ('yellow', 29), ('orange', 34), ('blue', 23), ('purple', 36)])

You can check if a key is in the dictionary by using `in` and `not in` :

In [83]:
print("purple" in marbles.keys())
print("white" not in marbles)

print(31 in marbles.values())

True
True
True

**Iterating a dictionary**

We can iterate through a dictionary using a for-loop and access the individual keys and their corresponding values. Let us see this with an example.

In [85]:
person = {"name": "Jessa", "country": "USA", "telephone": 1178}
person[0]

KeyError: ignored

In [87]:
person = {"name": "Jessa", "country": "USA", "telephone": 1178}

# Iterating the dictionary using for-loop
#print('key', ':', 'value')
#for key in person:
#    print(key, ':', person[key])

# using items() method
print('key', ':', 'value')
for key_value in person.items():
    # first is key, and second is value
    print(key_value[0], key_value[1])

key : value
name Jessa
country USA
telephone 1178

## 6. Conversation of collections


### Implicit conversions

If we try to iterate over a collection in a `for` loop (something we'll discuss in the next chapter), Python will try to convert it into something we can browse if it knows how to do so. For example, the `dict` we saw above are not actually iterators, but Python knows how to turn them into iterators, so we can use them in an `for` loop without having to convert them ourselves.

Sometimes the iterator we get by default may not be what we expect, if we're running through a dictionary in a `for` loop, we're running through the keys. If what we really want to do is iterate over values, or key and value pairs, we will have to specify this ourselves using the `values` and `items` functions.


### Explicit conversions

We can convert the different types of sequences by using the `built-in` functions (corresponding to the type) to convert the sequences into the desired types:

In [92]:
animals = ['cat', 'dog', 'goldfish', 'canary', 'cat']
animals_set = set(animals)
print(animals_set)
animals_unique_list = list(animals_set)
print(animals_unique_list)
animals_unique_tuple = tuple(animals_unique_list)
print(animals_unique_tuple)

{'dog', 'canary', 'goldfish', 'cat'}
['dog', 'canary', 'goldfish', 'cat']
('dog', 'canary', 'goldfish', 'cat')

In [94]:
marbles = {"red": 34, "green": 30, "brown": 31, "yellow": 29 }
colours = list(marbles) # the keys will be used by default
print(colours)
colours1 = list(marbles.values())
print(colours1)

['red', 'green', 'brown', 'yellow']
[34, 30, 31, 29]

In [96]:
marbles = {"red": 34, "green": 30, "brown": 31, "yellow": 29 }
colours = list(marbles) # the keys will be used by default
counts = tuple(marbles.values()) # but we can use a view to get the values
marbles_set = set(marbles.items()) # or the key-value pairs


# Python doesn't know how to convert this into a dictionary
#

# but this will work
dict([(1, 2), (3, 4)])

{1: 2, 3: 4}